language: python

dist: precise  # fix installing Python 3.3, 3.2
sudo: false

env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py27-django1.6-drf2.4.3
  - TOX_ENV=py27-django1.6-drf2.4.4
  - TOX_ENV=py27-django1.6-drf3.0
  - TOX_ENV=py27-django1.6-drf3.1
  - TOX_ENV=py27-django1.7-drf2.4.3
  - TOX_ENV=py27-django1.7-drf2.4.4
  - TOX_ENV=py27-django1.7-drf3.0
  - TOX_ENV=py27-django1.7-drf3.1
  - TOX_ENV=py27-django1.7-drf3.2
  - TOX_ENV=py27-django1.7-drf3.3
  - TOX_ENV=py27-django1.8-drf3.0
  - TOX_ENV=py27-django1.8-drf3.1
  - TOX_ENV=py27-django1.8-drf3.2
  - TOX_ENV=py27-django1.8-drf3.3
  - TOX_ENV=py27-django1.9-drf3.2
  - TOX_ENV=py27-django1.9-drf3.3
  - TOX_ENV=py27-django1.10-drf3.4
  - TOX_ENV=py27-django1.11-drf3.4
  - TOX_ENV=py33-django1.6-drf2.4.3
  - TOX_ENV=py33-django1.6-drf2.4.4
  - TOX_ENV=py33-django1.6-drf3.0
  - TOX_ENV=py33-django1.6-drf3.1
  - TOX_ENV=py33-django1.7-drf2.4.3
  - TOX_ENV=py33-django1.7-drf2.4.4
  - TOX_ENV=py33-django1.7-drf3.0
  - TOX_ENV=py33-django1.7-drf3.1
  - TOX_ENV=py33-django1.7-drf3.2
  - TOX_ENV=py33-django1.7-drf3.3
  - TOX_ENV=py33-django1.8-drf3.0
  - TOX_ENV=py33-django1.8-drf3.1
  - TOX_ENV=py33-django1.8-drf3.2
  - TOX_ENV=py33-django1.8-drf3.3
  - TOX_ENV=py34-django1.6-drf2.4.3
  - TOX_ENV=py34-django1.6-drf2.4.4
  - TOX_ENV=py34-django1.6-drf3.0
  - TOX_ENV=py34-django1.6-drf3.1
  - TOX_ENV=py34-django1.7-drf2.4.3
  - TOX_ENV=py34-django1.7-drf2.4.4
  - TOX_ENV=py34-django1.7-drf3.0
  - TOX_ENV=py34-django1.7-drf3.1
  - TOX_ENV=py34-django1.7-drf3.2
  - TOX_ENV=py34-django1.7-drf3.3
  - TOX_ENV=py34-django1.10-drf3.4
  - TOX_ENV=py34-django1.11-drf3.4
  - TOX_ENV=py34-django1.8-drf3.0
  - TOX_ENV=py34-django1.8-drf3.1
  - TOX_ENV=py34-django1.8-drf3.2
  - TOX_ENV=py34-django1.8-drf3.3
  - TOX_ENV=py34-django1.9-drf3.2
  - TOX_ENV=py34-django1.9-drf3.3
  - TOX_ENV=py35-django1.8-drf3.2
  - TOX_ENV=py35-django1.8-drf3.3
  - TOX_ENV=py35-django1.9-drf3.2
  - TOX_ENV=py35-django1.9-drf3.3
  - TOX_ENV=py35-django1.10-drf3.4
  - TOX_ENV=py35-django1.11-drf3.4

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
