language: python
python: 3.5

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.2
      - python3.3

env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py27-django1.6-drf2.4.3
  - TOX_ENV=py27-django1.6-drf2.4.4
  - TOX_ENV=py27-django1.6-drf3.0
  - TOX_ENV=py27-django1.6-drf3.1
  - TOX_ENV=py27-django1.7-drf2.4.3
  - TOX_ENV=py27-django1.7-drf2.4.4
  - TOX_ENV=py27-django1.7-drf3.0
  - TOX_ENV=py27-django1.7-drf3.1
  - TOX_ENV=py27-django1.7-drf3.2
  - TOX_ENV=py27-django1.7-drf3.3
  - TOX_ENV=py27-django1.8-drf3.0
  - TOX_ENV=py27-django1.8-drf3.1
  - TOX_ENV=py27-django1.8-drf3.2
  - TOX_ENV=py27-django1.8-drf3.3
  - TOX_ENV=py27-django1.9-drf3.2
  - TOX_ENV=py27-django1.9-drf3.3
  - TOX_ENV=py32-django1.6-drf2.4.3
  - TOX_ENV=py32-django1.6-drf2.4.4
  - TOX_ENV=py32-django1.6-drf3.0
  - TOX_ENV=py32-django1.6-drf3.1
  - TOX_ENV=py32-django1.7-drf2.4.3
  - TOX_ENV=py32-django1.7-drf2.4.4
  - TOX_ENV=py32-django1.7-drf3.0
  - TOX_ENV=py32-django1.7-drf3.1
  - TOX_ENV=py32-django1.8-drf3.0
  - TOX_ENV=py32-django1.8-drf3.1
  - TOX_ENV=py33-django1.6-drf2.4.3
  - TOX_ENV=py33-django1.6-drf2.4.4
  - TOX_ENV=py33-django1.6-drf3.0
  - TOX_ENV=py33-django1.6-drf3.1
  - TOX_ENV=py33-django1.7-drf2.4.3
  - TOX_ENV=py33-django1.7-drf2.4.4
  - TOX_ENV=py33-django1.7-drf3.0
  - TOX_ENV=py33-django1.7-drf3.1
  - TOX_ENV=py33-django1.7-drf3.2
  - TOX_ENV=py33-django1.7-drf3.3
  - TOX_ENV=py33-django1.8-drf3.0
  - TOX_ENV=py33-django1.8-drf3.1
  - TOX_ENV=py33-django1.8-drf3.2
  - TOX_ENV=py33-django1.8-drf3.3
  - TOX_ENV=py34-django1.6-drf2.4.3
  - TOX_ENV=py34-django1.6-drf2.4.4
  - TOX_ENV=py34-django1.6-drf3.0
  - TOX_ENV=py34-django1.6-drf3.1
  - TOX_ENV=py34-django1.7-drf2.4.3
  - TOX_ENV=py34-django1.7-drf2.4.4
  - TOX_ENV=py34-django1.7-drf3.0
  - TOX_ENV=py34-django1.7-drf3.1
  - TOX_ENV=py34-django1.7-drf3.2
  - TOX_ENV=py34-django1.7-drf3.3
  - TOX_ENV=py34-django1.8-drf3.0
  - TOX_ENV=py34-django1.8-drf3.1
  - TOX_ENV=py34-django1.8-drf3.2
  - TOX_ENV=py34-django1.8-drf3.3
  - TOX_ENV=py34-django1.9-drf3.2
  - TOX_ENV=py34-django1.9-drf3.3
  - TOX_ENV=py35-django1.8-drf3.2
  - TOX_ENV=py35-django1.8-drf3.3
  - TOX_ENV=py35-django1.9-drf3.2
  - TOX_ENV=py35-django1.9-drf3.3

matrix:
  fast_finish: true

install:
  - if [[ $TOX_ENV == py32* ]]; then pip install pip\<8.0.0 virtualenv\<14.0.0; fi
  - pip install tox

script:
  - tox -e $TOX_ENV
